<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML>
<HEAD>
<style>
</style>
<TITLE> Aqua-Designs </TITLE>
<link href='https://fonts.googleapis.com/css?family=Saira' rel='stylesheet'>
<link rel="stylesheet" href="no.css">
<META NAME="Generator" CONTENT="EditPlus">
<META NAME="Author" CONTENT="">
<META NAME="Keywords" CONTENT="">
<META NAME="Description" CONTENT="">
<meta name="viewport" content="width=device-width">
</HEAD>

<BODY>
<div class="main-box">
<div class="headermenue w3-container w3-center w3-content" style="border-bottom: 1px solid #ccc">
    <a class="saria" style="margin-right: 60px;" href="index.phtml">AQUA-DESIGNS</a>
    <a href="index.phtml">Home</a>
    <a href="porto.phtml">Portfolio</a>
    <a href="#">About</a>
    <a href="#">Contact</a>
</div>

<div class="content" >
    <div class="w3-container w3-center w3-content w3-max-width" style="border-bottom: 1px solid #ccc; margin-bottom: 15px;">
        <p class="w3-justify upper">
            <strong>Hello on <span class="steelblue">AQUA-DESIGNS</span></strong><br/>
            My Style, My Art
        </p>
    </div>
</div>
<!---->

<div  style="width: 98%; margin: 0px auto;" >
<!-- Slideshow container -->
<div class="slideshow-container">

  <!-- Full-width images with number and caption text -->
  <div class="mySlides fade">
    <img src="image/1.jpg" style="width:100%">
    <div class="text saria center white"></div>
  </div>

  <div class="mySlides fade">
    <img src="image/2.jpg" style="width:100%">
    <div class="text saria center white"></div>
  </div>

  <div class="mySlides fade">
    <img src="image/3.jpg" style="width:100%">
    <div class="text saria center white"></div>
  </div>

  <!-- Next and previous buttons -->
  <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
  <a class="next" onclick="plusSlides(1)">&#10095;</a>
</div>


</div>



<div class="content ">
    <div class="w3-container w3-center w3-content w3-max-width">
    <p class="w3-justify">
    Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.
    At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
    Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat,
    sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est
    Lorem ipsum dolor sit amet.</p>
    </div>
    <div class="w3-container w3-center w3-content w3-max-width ">
        <div class="image " style="border: 1px solid #ccc">
            <img src="image/chill_by_AquaDesigns.jpg"/>
        </div>
    </div>
</div>
<div class="content ">
    <div class="w3-container w3-center w3-content w3-max-width" style="border-bottom: 1px solid #ccc; margin-bottom: 15px;">
<p class="w3-justify">
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. 
At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. 
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, 
sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est 
Lorem ipsum dolor sit amet.</p>
</div>
<div class="w3-container w3-center w3-content 3-headed">
<div class="image_3head" style="border: 0px solid #ccc"> <img src="image/chill_by_AquaDesigns.jpg"/> </div>	
<div class="image_3head" style="border: 0px solid #ccc"> <img src="image/chill_by_AquaDesigns.jpg"/> </div>	
<div class="image_3head" style="border: 0px solid #ccc"> <img src="image/chill_by_AquaDesigns.jpg"/> </div>
</div>
<div class="w3-container w3-center w3-content" >
<p class="w3-justify">
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. 
At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. 
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, 
sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est 
Lorem ipsum dolor sit amet.</p>
</div>
</div>
<div class="footer w3-container w3-center  grey">
<div class="w3-container w3-center w3-content">
    <p class="w3-justify">
        Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.
        At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
        Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat,
        sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est
        Lorem ipsum dolor sit amet.</p>
</div>
</div>

<script>
var slideIndex = 1;
showSlides(slideIndex);

function plusSlides(n) {
  showSlides(slideIndex += n);
}

function currentSlide(n) {
  showSlides(slideIndex = n);
}

function showSlides(n) {
  var i;
  var slides = document.getElementsByClassName("mySlides");
  var dots = document.getElementsByClassName("dot");
  if (n > slides.length) {slideIndex = 1}    
  if (n < 1) {slideIndex = slides.length}
  for (i = 0; i < slides.length; i++) {
      slides[i].style.display = "none";  
  }
  for (i = 0; i < dots.length; i++) {
      dots[i].className = dots[i].className.replace(" active", "");
  }
  slides[slideIndex-1].style.display = "block";  
  dots[slideIndex-1].className += " active";
}
</script>
</div>
</BODY>
</HTML>
