<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML>
<HEAD>
<style>
</style>
<TITLE> Aqua-Designs </TITLE>
<link href='https://fonts.googleapis.com/css?family=Saira' rel='stylesheet'>
<link rel="stylesheet" href="no.css">
<META NAME="Generator" CONTENT="EditPlus">
<META NAME="Author" CONTENT="">
<META NAME="Keywords" CONTENT="">
<META NAME="Description" CONTENT="">
<meta name="viewport" content="width=device-width">
</HEAD>

<BODY>
<div class="headermenue">

<a href="index.phtml">Home</a>
<a href="porto.phtml">Portfolio</a>
<a href="#">About</a>
<a href="#">Contact</a>
</div>
<div class="header center white" style="width: 100%;">
AQUA-DESIGNS
</div>
<div  style="width: 100%;">
<!-- Slideshow container -->
<div class="slideshow-container">

  <!-- Full-width images with number and caption text -->
  <div class="mySlides fade">
    <div class="numbertext">1 / 3</div>
    <img src="image/chill_by_AquaDesigns.jpg" style="width:100%">
    <div class="text center white">Caption Text</div>
  </div>

  <div class="mySlides fade">
    <div class="numbertext">2 / 3</div>
    <img src="image/chill_by_AquaDesigns.jpg" style="width:100%">
    <div class="text center white">Caption Two</div>
  </div>

  <div class="mySlides fade">
    <div class="numbertext">3 / 3</div>
    <img src="image/chill_by_AquaDesigns.jpg" style="width:100%">
    <div class="text center white">Caption Three</div>
  </div>

  <!-- Next and previous buttons -->
  <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
  <a class="next" onclick="plusSlides(1)">&#10095;</a>
</div>
<br>

<!-- The dots/circles -->
<div style="text-align:center">
  <span class="dot" onclick="currentSlide(1)"></span> 
  <span class="dot" onclick="currentSlide(2)"></span> 
  <span class="dot" onclick="currentSlide(3)"></span> 
</div>
</div>

<div class="menue" style="width: 100%;">
 <a href="#"><div class="tas" style="float: left;">Left Stuff</div></a>
 <a href="#"><div class="tas" style="float: left;">Middle Stuff</div></a>
 <a href="#"><div class="tas" style="float: left;">Right Stuff</div></a>
 <br style="clear: left;" />
</div>
<div class="header-small">&nbsp;</div>
<div class="content">
<div class="w3-container w3-center w3-content w3-max-width">
<p class="w3-justify">
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. 
At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. 
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, 
sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est 
Lorem ipsum dolor sit amet.</p>
</div>
<div class="w3-container w3-center w3-content w3-max-width ">
	<div class="image " style="border: 1px solid #ccc"> <img src="image/chill_by_AquaDesigns.jpg"/></div>	
</div>
<div class="w3-container w3-center w3-content">
<p class="w3-justify">
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. 
At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. 
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, 
sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est 
Lorem ipsum dolor sit amet.</p>
</div>
<div class="w3-container w3-center w3-content 3-headed">
<div class="image_3head" style="border: 0px solid #ccc"> <img src="image/chill_by_AquaDesigns.jpg"/> </div>	
<div class="image_3head" style="border: 0px solid #ccc"> <img src="image/chill_by_AquaDesigns.jpg"/> </div>	
<div class="image_3head" style="border: 0px solid #ccc"> <img src="image/chill_by_AquaDesigns.jpg"/> </div>
</div>
<div class="w3-container w3-center w3-content" >
<p class="w3-justify">
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. 
At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. 
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, 
sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est 
Lorem ipsum dolor sit amet.</p>
</div>

<div class="footer w3-container w3-center w3-content">
<p class="w3-justify">
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. 
At vero eos et accusam et jus


</p>

</div>

<script>
var slideIndex = 1;
showSlides(slideIndex);

function plusSlides(n) {
  showSlides(slideIndex += n);
}

function currentSlide(n) {
  showSlides(slideIndex = n);
}

function showSlides(n) {
  var i;
  var slides = document.getElementsByClassName("mySlides");
  var dots = document.getElementsByClassName("dot");
  if (n > slides.length) {slideIndex = 1}    
  if (n < 1) {slideIndex = slides.length}
  for (i = 0; i < slides.length; i++) {
      slides[i].style.display = "none";  
  }
  for (i = 0; i < dots.length; i++) {
      dots[i].className = dots[i].className.replace(" active", "");
  }
  slides[slideIndex-1].style.display = "block";  
  dots[slideIndex-1].className += " active";
}
</script>
</BODY>
</HTML>
