<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML>
<HEAD>
<style>
</style>
<TITLE> Aqua-Designs - Portfolio</TITLE>
<link href='https://fonts.googleapis.com/css?family=Saira' rel='stylesheet'>
<link rel="stylesheet" href="no.css">
<META NAME="Generator" CONTENT="EditPlus">
<META NAME="Author" CONTENT="">
<META NAME="Keywords" CONTENT="">
<META NAME="Description" CONTENT="">
<meta name="viewport" content="width=device-width">
</HEAD>

<BODY>
<div class="headermenue">

<a href="index.phtml">Home</a>
<a href="porto.phtml">Portfolio</a>
<a href="#">About</a>
<a href="#">Contact</a>
</div>
<div class="header center white" style="width: 100%;">
<!--AQUA-DESIGNS--> &nbsp;
</div>

<!--<div class="menue" style="width: 100%;">
 <a href="#"><div class="tas" style="float: left;">Left Stuff</div></a>
 <a href="#"><div class="tas middle-border"style="float: left;">Middle Stuff</div></a>
 <a href="#"><div class="tas" style="float: left;">Right Stuff</div></a>
 <br style="clear: left;" />
</div>-->
<div class="header-small">&nbsp;</div>
<div class="w3-container w3-center w3-content" >
<p class="w3-justify">
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. 
At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. 
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, 
sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est 
Lorem ipsum dolor sit amet.</p>
</div>

<div class="w3-container w3-center w3-content">
<p class="w3-justify">
<div class="image_porto" style="border: 0px solid #ccc"> <img src="image/chill_by_AquaDesigns.jpg"/> </div>	
<div class="image_porto" style="border: 0px solid #ccc"> <img src="image/chill_by_AquaDesigns.jpg"/> </div>	
<div class="image_porto" style="border: 0px solid #ccc">  <img src="image/chill_by_AquaDesigns.jpg"/> </div>	
<div class="image_porto" style="border: 0px solid #ccc"> <img src="image/chill_by_AquaDesigns.jpg"/> </div>	</p>
</div>

<div class="w3-container w3-center w3-content" >
<p class="w3-justify">
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. 
At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. 
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, 
sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est 
Lorem ipsum dolor sit amet.</p>
</div>

<div class="footer w3-container w3-center w3-content">
<p class="w3-justify">
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. 
At vero eos et accusam et jus
</p>
</BODY>

</HTML>
